### ISSUE TITLE
couple of questions and request

### ISSUE THREAD

**Issue by JunkyardCat** [requinDr/tsukiweb-public#12]
also a quick switch between the two language. also i checked and there was a japanese version  but is that the original one or a translated one from english?

is there a way to make the text selectable? also a way to select it without moving the dialogue forward?
also is there a way to quickly change from one language to another while in game?

**Comment by requinDr** [comment]
The Japanese version is the original.

The text could be made selectable, but it would cause issues. It would play the next line when starting the selection, and on double clicks it would select everything. For these reasons, the text won't be made selectable.
If you have a particular reason for wanting the text to be selectable such as an accesibility issue, please tell.

Changing the language in-game caused problems before the website was published, which is why the Advanced tab, where the language setting is, isn't visible in-game. However, things have changed a lot since then, so I'll try to see if it's more feasible now.

**Comment by JunkyardCat** [comment]
> If you have a particular reason for wanting the text to be selectable such as an accesibility issue, please tell.

for learning the language

**Comment by requinDr** [comment]
I see. Then I'll allow copying from History for now

**Comment by requinDr** [comment]
@JunkyardCat update is out, selection is now possible in History

**Comment by JunkyardCat** [comment]
ealier you mentioned that you will try to see if changing the language would be a problem so was wondering if changing the language in game possible or no

**Comment by requinDr** [comment]
Not possible at the moment
